### ISSUE TITLE
Non-array attributes

### ISSUE THREAD

**Issue by Pamblam** [GrumpyCrouton/GrumpyPDO#12]
## Expected Behavior

I expect the query to work

## Actual Behavior

The query doesn't work :(

## Steps to Reproduce the Problem

  1.  `$pdo = new GrumpyPDO($host, $user, $pass, $db, PDO::CASE_LOWER)`

## Specifications

Saw your project on Codereview and was creeping looking for a pull request for Hacktoberfest but I don't see anything I can do.. I did notice this little issue tho, if a non-null, non-array value is passed to the constructor for the $attributes parameter your code won't catch it and PDO will end up throwing an error.

Problem is 

`if($attributes == NULL && !is_array($attributes)) {`

should be 

`if($attributes == NULL || !is_array($attributes)) {`

which should really just be

`if(!is_array($attributes)) {`

cheers!

**Comment by GrumpyCrouton** [comment]
Hmm.. What I was attempting was to make it so that passing `NULL` would force PDO to not use any custom attributes, but you are right, with the current code this would error out. So what I think I should do is, change it to what you have suggested, but inside the statement check if the value is `NULL`, if it is, set `$attributes` to an empty array, if it is not, then set `$attributes` to the GrumpyPDO defaults.

What are your thoughts on this? I don't think that passing a "a non-null, non-array value" to the constructor should cancel out the defaults of GrumpyPDO.

@Pamblam

**Comment by Pamblam** [comment]
I would just check to see if the `$attributes` param is [`empty`](http://php.net/manual/en/function.empty.php), if so, use the GrumpyPDO defaults. `empty` is really all you need since it returns true if you pass it null, 0, an undefined variable, or an empty array.

Edit: on second thought, you would also have to make sure it's an array so..

`if(empty($attributes) || !is_array($attributes)) /* use GrumpPDO default */`

**Comment by GrumpyCrouton** [comment]
No, because that eliminates the possibility to not use the defaults. Check my latest pull request, it will show better what I mean because I've already implemented it.

Basically, if `NULL` is passed, GrumpyPDO doesn't add any attributes to the connection, not even the defaults. I want this option so people that want to rely on the defaults that they have set elsewhere, they have the ability to do so.

If an empty array is passed, it uses the defaults.

If an array of attributes it passed, it uses that array of attributes.

**Comment by Pamblam** [comment]
I see what you mean. Looks like you've got it sorted then.

**Comment by GrumpyCrouton** [comment]
Thank you very much for your issue report!
